import "./globals.css";
import Header from "@/components/Header/Header";
import Menu from "@/components/Menu/Menu";
import { Wrapper } from "@/components/Wrapper/Wrapper";
import { useMenuStore } from "@/stores/menu";
import { MainSection } from "@/components/MainSection/MainSection";
import { Footer } from "@/components/Footer/Footer";

export const metadata = {
  title: 'Portfólio - Ryan Guimarães',
  description: 'Generated by Next.js',
   icons: {
    icon: "/logo.svg",
  },
}



export default function RootLayout({ children }) {
  
  return (

    <html lang="pt-BR">
      <body>
        <div className="bg-blue-500 text-slate-950">
          <Menu/>
          <Wrapper>
            <Header/>
            <MainSection>
            {children}
            </MainSection>
            <Footer/>
          </Wrapper>
        </div>
      </body>
    </html>
  )
}
