
import "./globals.css";
import Header from "@/components/header/Header";
import Menu from "@/components/menu/Menu";
import { Wrapper } from "@/components/wrapper/wrapper";
import { useMenuStore } from "@/stores/menu";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-blue-500">
        <Menu/>
        <Wrapper>
          <Header/>
          <main>
           {children}
          </main>
        </Wrapper>
      </body>
    </html>
  )
}
